;===================================================================================================
; Defines memory-mapped addresses for joystick controllers and bit values for gamepad buttons.
;===================================================================================================
JOYPAD1    = $4016
JOYPAD2    = $4017

PAD_A      = $01
PAD_B      = $02
PAD_SELECT = $04
PAD_START  = $08
PAD_U      = $10
PAD_D      = $20
PAD_L      = $40
PAD_R      = $80
