;===================================================================================================
; Defines memory-mapped addresses for joystick controllers and bit values for gamepad buttons.
;===================================================================================================
JOYPAD1    = $4016
JOYPAD2    = $4017

PAD_R      = %00000001
PAD_L      = %00000010
PAD_D      = %00000100
PAD_U      = %00001000
PAD_START  = %00010000
PAD_SELECT = %00100000
PAD_B      = %01000000
PAD_A      = %10000000
