;===================================================================================================
; Misc constants for text operations and other general purposes. 
;===================================================================================================
NEXT_SLIDE        = $01
NEWLINE           = $02

MAX_SLIDES        = 6
MAX_SLIDE_INDEX   = (MAX_SLIDES-1)*2
MAX_SLIDE_COLUMNS = 32
MAX_SLIDE_ROWS    = 26

FIRE_RATE         = 20
