;===================================================================================================
; Misc constants for text operations and other general purposes. 
;===================================================================================================
NEXT_SLIDE        = 0
NEWLINE           = $A

MAX_SLIDES        = 4
MAX_SLIDE_INDEX   = (MAX_SLIDES-1)*2
MAX_SLIDE_COLUMNS = 32
MAX_SLIDE_ROWS    = 30

FIRE_RATE         = 20
