;===================================================================================================
; Defines memory-mapped addresses for controlling and interfacing with the PPU.
;===================================================================================================
PPU_CONTROL = $2000
PPU_MASK    = $2001
PPU_STATUS  = $2002
OAM_ADDRESS = $2003
OAM_DATA    = $2004
PPU_SCROLL  = $2005
PPU_ADDRESS = $2006
PPU_DATA    = $2007
OAM_DMA     = $4014

PAL_ADDRESS = $3F00
NT1_ADDRESS = $2000
