;===================================================================================================
; Sprite constants 
;===================================================================================================
PLAYER_SPRITE_COUNT               = 5
TEXT_ARROW_SPRITE_COUNT           = 1

; OAM offsets
PLAYER_OAM_OFFSET                 = 0 
PLAYER_CIGAR_TILE_OAM_OFFSET      = 1
PLAYER_LEFT_HEAD_TILE_OAM_OFFSET  = 5
PLAYER_RIGHT_HEAD_TILE_OAM_OFFSET = 9
PLAYER_LEFT_BODY_TILE_OAM_OFFSET  = 13
PLAYER_RIGHT_BODY_TILE_OAM_OFFSET = 17
TEXT_ARROW_OAM_OFFSET             = 20

; Pattern table 1
PLAYER_STAND_TILE_IDX             = $02
PLAYER_CIGAR_LEFT_TILE_IDX        = $03
PLAYER_SUNGLASSES_TILE_IDX        = $11
PLAYER_WALK_TILE_IDX              = $12
PLAYER_CIGAR_RIGHT_TILE_IDX       = $13
