;===================================================================================================
; Main container for all constants used in the project.
;===================================================================================================
.include "constants/apu.inc"
.include "constants/input.inc"
.include "constants/misc.inc"
.include "constants/nmi.inc"
.include "constants/ppu.inc"
