;===================================================================================================
; Main container for all macros used in the project.
;===================================================================================================
.include "macros/ppu.inc"
.include "macros/sound.inc"
.include "macros/slides.inc"
.include "macros/shooting.inc"
.include "macros/utils.inc"
.include "macros/player.inc"
.include "macros/menu.inc"
.include "macros/sprites.inc"
